# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- Desarrollo

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: |
      **
      !.git/**
      !.env/**
    TargetFolder: '/home/magotteauxaeurus/public_html/'
    CleanTargetFolder: true
    OverWrite: true

- task: SSH@0
  inputs:
    sshEndpoint: 'Desarrollo'
    runOptions: 'commands'
    commands: |
      cd /home/magotteauxaeurus/public_html/ && chown -fR magotteauxaeurus:magotteauxaeurus . && php artisan migrate
    readyTimeout: '20000'